/*
 * Content script entry point. Runs at document_start in every Fabric / Power BI frame.
 *
 * Strategy:
 *  - A <style> element (document + every open shadow root) holds rules generated by buildCss().
 *  - Elements whose *direct* text (or input value) matches the detector get MASK_ATTR. Masking the
 *    direct parent of the text keeps the blurred area tight and never touches framework-owned
 *    text nodes (no wrapping, which would break Angular/React reconciliation).
 *  - A MutationObserver re-evaluates changed elements synchronously in its callback, i.e. before
 *    the next paint, so new content never flashes unmasked. Elements recycled by virtual
 *    scrolling are re-evaluated and un-masked when their text no longer matches.
 */
(function (root) {
  'use strict';

  const SKIP_TAGS = new Set(['SCRIPT', 'STYLE', 'NOSCRIPT', 'TEMPLATE', 'HEAD', 'TITLE', 'META', 'LINK']);
  const STYLE_MARKER = 'data-fabric-mask-style';
  const INPUT_SELECTOR = 'input:not([type="password"]):not([type="hidden"]):not([type="checkbox"]):not([type="radio"]), textarea';
  const INPUT_POLL_MS = 1000;
  // Text split across inline formatting (search highlights, <wbr> in long IDs) is checked on the
  // combined textContent of small, inline-only elements.
  const INLINE_TAGS = new Set(['SPAN', 'B', 'I', 'EM', 'STRONG', 'MARK', 'WBR', 'U', 'SMALL', 'CODE', 'SUB', 'SUP']);
  const MAX_COMBINED_TEXT = 512;
  // Monaco (notebooks, SQL/KQL editors) splits long tokens into several <span>s, so a GUID inside a
  // long OneLake path can straddle two spans. Editor lines are therefore tested as a whole.
  const CODE_LINE_SELECTOR = '.view-line';

  function createMasker({ window, chrome, FabricMask: FM }) {
    const document = window.document;
    const MSG = FM.MESSAGES;
    const MASK_ATTR = FM.MASK_ATTR;
    const isTopFrame = (() => {
      try {
        return window.top === window;
      } catch {
        return false;
      }
    })();

    let settings = FM.normalizeSettings(null); // mask with defaults until stored settings arrive
    let detector = FM.createDetector(settings);
    let css = FM.buildCss(settings);
    const roots = new Set(); // Document and ShadowRoots we observe
    const styleEls = new Map(); // root -> <style>
    const svgEls = new Map(); // root -> hidden <svg> with the mosaic filter
    let pollTimer = null;
    let lastInputValues = new WeakMap(); // input -> last evaluated value
    let pageTitle = null;
    let lastSetTitle = null;
    let picker = null;

    const observer = new window.MutationObserver(onMutations);
    const OBSERVE_OPTIONS = { childList: true, subtree: true, characterData: true };

    // ---------------------------------------------------------------- styles

    function ensureStyle(rootNode) {
      const parent = rootNode === document ? document.documentElement : rootNode;
      let el = styleEls.get(rootNode);
      if (!el) {
        el = document.createElement('style');
        el.setAttribute(STYLE_MARKER, '');
        el.textContent = css;
        styleEls.set(rootNode, el);
      }
      if (!el.isConnected && parent) parent.appendChild(el);
      // filter: url(#id) resolves within the element's own tree, so every root gets the filter.
      let svg = svgEls.get(rootNode);
      if (!svg) {
        svg = FM.renderPixelateSvg(document, FM.pixelSize(settings));
        svg.setAttribute(STYLE_MARKER, '');
        svgEls.set(rootNode, svg);
      }
      if (!svg.isConnected && parent) parent.appendChild(svg);
    }

    function applyCss() {
      css = FM.buildCss(settings);
      const size = FM.pixelSize(settings);
      for (const [rootNode, el] of styleEls) {
        if (el.textContent !== css) el.textContent = css;
        const svg = svgEls.get(rootNode);
        if (svg) FM.renderPixelateSvg(document, size, svg);
        ensureStyle(rootNode);
      }
    }

    // ------------------------------------------------------------- detection

    function isFormField(el) {
      return (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') && el.matches(INPUT_SELECTOR);
    }

    function isSensitive(el) {
      if (!detector.active) return false;
      let textNodes = 0;
      for (let n = el.firstChild; n; n = n.nextSibling) {
        if (n.nodeType !== 3) continue;
        textNodes++;
        if (detector.test(n.data)) return true;
      }
      // Adjacent text nodes (e.g. Angular interpolation "{{user}}@{{domain}}")
      if (textNodes > 1 && detector.test(ownText(el))) return true;
      if (isFormField(el) && detector.test(el.value)) return true;
      if (el.matches(CODE_LINE_SELECTOR) && detector.test(el.textContent)) return true;
      if (el.firstElementChild && hasOwnText(el) && hasOnlyInlineChildren(el)) {
        const text = el.textContent;
        if (text.length <= MAX_COMBINED_TEXT && detector.test(text)) return true;
      }
      return false;
    }

    function ownText(el) {
      let text = '';
      for (let n = el.firstChild; n; n = n.nextSibling) if (n.nodeType === 3) text += n.data;
      return text;
    }

    function hasOwnText(el) {
      for (let n = el.firstChild; n; n = n.nextSibling) {
        if (n.nodeType === 3 && n.data.trim()) return true;
      }
      return false;
    }

    function hasOnlyInlineChildren(el) {
      for (let c = el.firstElementChild; c; c = c.nextElementSibling) {
        if (!INLINE_TAGS.has(c.tagName) || c.firstElementChild) return false;
      }
      return true;
    }

    function evaluate(el) {
      if (!el || el.nodeType !== 1 || SKIP_TAGS.has(el.tagName)) return;
      if (el.hasAttribute(STYLE_MARKER)) return;
      const sensitive = settings.enabled && isSensitive(el);
      if (sensitive) {
        if (!el.hasAttribute(MASK_ATTR)) {
          el.setAttribute(MASK_ATTR, '');
          const rootNode = el.getRootNode();
          if (rootNode !== document && !styleEls.has(rootNode)) styleShadowRootIfNeeded(rootNode);
        }
      } else if (el.hasAttribute(MASK_ATTR)) {
        el.removeAttribute(MASK_ATTR);
      }
    }

    function scan(node) {
      if (!node) return;
      if (node.nodeType === 3) {
        evaluate(node.parentElement);
        return;
      }
      if (node.nodeType === 1) {
        if (SKIP_TAGS.has(node.tagName)) return;
        evaluate(node);
        attachShadowOf(node);
      } else if (node.nodeType !== 9 && node.nodeType !== 11) {
        return;
      }
      const walker = document.createTreeWalker(node, 1 /* SHOW_ELEMENT */, {
        acceptNode: (el) => (SKIP_TAGS.has(el.tagName) || el.hasAttribute(STYLE_MARKER) ? 2 /* REJECT subtree */ : 1)
      });
      for (let el = walker.nextNode(); el; el = walker.nextNode()) {
        evaluate(el);
        attachShadowOf(el);
      }
    }

    function shadowRootOf(el) {
      if (el.shadowRoot) return el.shadowRoot;
      // Closed shadow roots are reachable for extensions via chrome.dom (custom elements only,
      // which are the only elements that can host one besides a few built-ins).
      if (el.localName.includes('-') && chrome && chrome.dom && chrome.dom.openOrClosedShadowRoot) {
        try {
          return chrome.dom.openOrClosedShadowRoot(el);
        } catch {
          return null;
        }
      }
      return null;
    }

    function attachShadowOf(el) {
      const sr = shadowRootOf(el);
      if (sr) attachRoot(sr);
    }

    // Shadow roots get the stylesheet + filter only once they contain something to mask. Fabric
    // has many small shadow roots (e.g. one per tooltip) that only hold a <slot>; giving each of
    // them a <style> and an <svg> made style recalculation needlessly expensive.
    function styleShadowRootIfNeeded(rootNode) {
      if (rootNode === document || styleEls.has(rootNode) || !roots.has(rootNode)) return;
      const selectors = FM.staticSelectorList(settings);
      if (rootNode.querySelector(`[${MASK_ATTR}]`) || (selectors && rootNode.querySelector(selectors))) {
        ensureStyle(rootNode);
      }
    }

    function attachRoot(rootNode) {
      if (roots.has(rootNode)) return;
      roots.add(rootNode);
      if (rootNode === document) ensureStyle(rootNode);
      observer.observe(rootNode, OBSERVE_OPTIONS);
      scan(rootNode);
      styleShadowRootIfNeeded(rootNode);
    }

    function rescanAll() {
      for (const rootNode of roots) scan(rootNode);
    }

    function touch(touched, el) {
      if (!el || el.nodeType !== 1) return;
      touched.add(el);
      touched.add(el.parentElement); // combined inline text may have changed
      const line = el.closest(CODE_LINE_SELECTOR);
      if (line) touched.add(line);
    }

    function onMutations(mutations) {
      const touched = new Set();
      let removedSomething = false;
      for (const m of mutations) {
        if (m.type === 'characterData') {
          touch(touched, m.target.parentElement);
        } else if (m.type === 'childList') {
          touch(touched, m.target);
          for (const added of m.addedNodes) {
            if (added.nodeType !== 1) continue;
            scan(added);
            const rootNode = added.getRootNode();
            if (rootNode !== document && !styleEls.has(rootNode)) styleShadowRootIfNeeded(rootNode);
          }
          if (m.removedNodes.length) removedSomething = true;
        }
      }
      for (const el of touched) evaluate(el);
      // Our stylesheet may have been removed directly, or with its parent (re-rendered <html>,
      // document.open() in about:blank frames).
      if (removedSomething) {
        for (const [rootNode, el] of styleEls) {
          const svg = svgEls.get(rootNode);
          if (!el.isConnected || (svg && !svg.isConnected)) ensureStyle(rootNode);
        }
      }
      if (isTopFrame) updateTitle();
    }

    // ---------------------------------------------------------------- inputs

    function pollInputs() {
      if (document.visibilityState === 'hidden') return; // background tab
      for (const rootNode of roots) {
        if (rootNode.host && !rootNode.host.isConnected) {
          // Detached shadow host: stop tracking (it is re-attached by scan() if it comes back).
          roots.delete(rootNode);
          styleEls.delete(rootNode);
          svgEls.delete(rootNode);
          continue;
        }
        if (!rootNode.querySelectorAll) continue;
        for (const el of rootNode.querySelectorAll(INPUT_SELECTOR)) {
          // Frameworks set .value without events; only re-test values that changed.
          if (lastInputValues.get(el) === el.value) continue;
          lastInputValues.set(el, el.value);
          evaluate(el);
        }
      }
    }

    function onInputEvent(event) {
      const path = typeof event.composedPath === 'function' ? event.composedPath() : [];
      evaluate(path[0] || event.target);
    }

    function updatePolling() {
      const shouldPoll = settings.enabled && detector.active;
      if (shouldPoll && !pollTimer) pollTimer = window.setInterval(pollInputs, INPUT_POLL_MS);
      if (!shouldPoll && pollTimer) {
        window.clearInterval(pollTimer);
        pollTimer = null;
      }
    }

    // ----------------------------------------------------------------- title

    function updateTitle() {
      const current = document.title;
      if (current !== lastSetTitle) pageTitle = current; // the page changed its title
      if (pageTitle === null) return;
      const desired = settings.enabled && settings.maskTitle ? detector.redact(pageTitle) : pageTitle;
      if (desired !== current) {
        lastSetTitle = desired;
        document.title = desired;
      } else {
        lastSetTitle = current;
      }
    }

    // -------------------------------------------------------------- settings

    function applySettings(raw) {
      settings = FM.normalizeSettings(raw);
      detector = FM.createDetector(settings);
      lastInputValues = new WeakMap();
      applyCss();
      rescanAll();
      for (const rootNode of roots) styleShadowRootIfNeeded(rootNode);
      updatePolling();
      if (isTopFrame) updateTitle();
    }

    function onStorageChanged(changes, areaName) {
      const next = FM.settingsFromChange(changes, areaName);
      if (next) applySettings(next);
    }

    // ---------------------------------------------------------------- picker

    function getPicker() {
      if (!picker) {
        picker = FM.createPicker({
          attr: FM.PICKER_ATTR,
          onPick: async (selector) => {
            let saved = true;
            try {
              await FM.updateSettings((s) => {
                if (!s.customSelectors.includes(selector)) s.customSelectors.push(selector);
                return s;
              });
            } catch {
              saved = false;
            }
            notifyPickerDone(saved ? selector : null);
          },
          onCancel: () => notifyPickerDone(null)
        });
      }
      return picker;
    }

    function notifyPickerDone(selector) {
      try {
        chrome.runtime.sendMessage({ type: MSG.PICKER_DONE, selector }).catch(() => {});
      } catch {
        // extension context invalidated (extension reloaded) – nothing to notify
      }
    }

    function onMessage(message, _sender, sendResponse) {
      if (!message || typeof message.type !== 'string') return undefined;
      switch (message.type) {
        case MSG.PING:
          if (isTopFrame) sendResponse({ ok: true, enabled: settings.enabled });
          return undefined;
        case MSG.START_PICKER:
          getPicker().start();
          return undefined;
        case MSG.STOP_PICKER:
          if (picker) picker.stop();
          return undefined;
        default:
          return undefined;
      }
    }

    // ----------------------------------------------------------------- start

    function start() {
      attachRoot(document);
      document.addEventListener('input', onInputEvent, true);
      document.addEventListener('change', onInputEvent, true);
      updatePolling();
      if (isTopFrame) updateTitle();
      if (chrome && chrome.storage) {
        chrome.storage.onChanged.addListener(onStorageChanged);
        FM.loadSettings().then(applySettings, () => applySettings(null));
      }
      if (chrome && chrome.runtime && chrome.runtime.onMessage) {
        chrome.runtime.onMessage.addListener(onMessage);
      }
    }

    function stop() {
      observer.disconnect();
      document.removeEventListener('input', onInputEvent, true);
      document.removeEventListener('change', onInputEvent, true);
      if (pollTimer) window.clearInterval(pollTimer);
      pollTimer = null;
      if (picker) picker.stop();
      if (chrome && chrome.storage) chrome.storage.onChanged.removeListener(onStorageChanged);
      if (chrome && chrome.runtime && chrome.runtime.onMessage) chrome.runtime.onMessage.removeListener(onMessage);
    }

    return {
      start,
      stop,
      applySettings,
      pollInputs,
      getSettings: () => settings
    };
  }

  const api = { createMasker };
  root.FabricMask = Object.assign(root.FabricMask || {}, api);
  if (typeof module !== 'undefined' && module.exports) module.exports = api;

  // Auto-start inside the extension (guards against double injection).
  const chromeApi = root.chrome;
  if (chromeApi && chromeApi.runtime && chromeApi.runtime.id && root.document && !root.__fabricMaskStarted) {
    root.__fabricMaskStarted = true;
    createMasker({ window: root, chrome: chromeApi, FabricMask: root.FabricMask }).start();
  }
})(typeof globalThis !== 'undefined' ? globalThis : this);
