/*
 * Content script entry point. Runs at document_start in every Fabric / Power BI frame, always in
 * the extension's isolated world – it never runs code in the page's JavaScript context.
 *
 * Strategy:
 *  - A <style> element (document, and shadow roots that contain something to mask) holds rules
 *    generated by buildCss().
 *  - Elements whose *direct* text (or input value, or whole Monaco line) matches the detector get
 *    MASK_ATTR. Masking the direct parent of the text keeps the masked area tight and never touches
 *    framework-owned text nodes (no wrapping, which would break Angular/React reconciliation).
 *  - A MutationObserver re-evaluates changed elements synchronously in its callback, i.e. before
 *    the next paint, so new content never flashes unmasked. Elements recycled by virtual
 *    scrolling are re-evaluated and un-masked when their text no longer matches.
 *  - Extras: learning person names from owner/admin fields, masking native tooltips (title),
 *    fake-data overlays (FAKE_ATTR + ::after), the "curtain" overlay and the preview badge.
 */
(function (root) {
  'use strict';

  const SKIP_TAGS = new Set(['SCRIPT', 'STYLE', 'NOSCRIPT', 'TEMPLATE', 'HEAD', 'TITLE', 'META', 'LINK']);
  const STYLE_MARKER = 'data-fabric-mask-style';
  const TITLE_ATTR = 'data-fabric-mask-title'; // original title of an element whose tooltip we masked
  // The masked title we wrote. Kept in the DOM (not a WeakMap) so a second instance of this script
  // (old + new copy right after an extension update) recognizes it instead of fighting over it.
  const TITLE_SET_ATTR = 'data-fabric-mask-title-set';
  const INPUT_SELECTOR = 'input:not([type="password"]):not([type="hidden"]):not([type="checkbox"]):not([type="radio"]), textarea';
  const POLL_MS = 1000;
  const LEARN_FLUSH_MS = 1500;
  const MAX_FAKE_TEXT = 2000;
  // In fake mode, undetected text around the matches stays readable only if it is a short label
  // ("Workspace ID: …"); longer text is scrambled so it reveals no more than the mosaic would.
  const MAX_CLEAR_LABEL = 24;
  const MASKED_TITLE = '••••••';
  // Text split across inline formatting (search highlights, <wbr> in long IDs) is checked on the
  // combined textContent of small, inline-only elements.
  const INLINE_TAGS = new Set(['SPAN', 'B', 'I', 'EM', 'STRONG', 'MARK', 'WBR', 'U', 'SMALL', 'CODE', 'SUB', 'SUP']);
  const MAX_COMBINED_TEXT = 512;
  // Monaco (notebooks, SQL/KQL editors) splits long tokens into several <span>s, so a GUID inside a
  // long OneLake path can straddle two spans. Editor lines are therefore tested as a whole.
  const CODE_LINE_SELECTOR = '.view-line';

  function createMasker({ window, chrome, FabricMask: FM }) {
    const document = window.document;
    const MSG = FM.MESSAGES;
    const MASK_ATTR = FM.MASK_ATTR;
    const FAKE_ATTR = FM.FAKE_ATTR;
    const FAKE_POS_ATTR = FM.FAKE_POS_ATTR;
    // Orphaned copies of this script (extension updated/reloaded) stop themselves.
    const startedWithRuntime = Boolean(chrome && chrome.runtime && chrome.runtime.id);
    const isTopFrame = (() => {
      try {
        return window.top === window;
      } catch {
        return false;
      }
    })();
    const t = (key, subs) => {
      try {
        return (chrome && chrome.i18n && chrome.i18n.getMessage(key, subs)) || key;
      } catch {
        return key;
      }
    };

    let settings = FM.normalizeSettings(null); // mask with defaults until stored settings arrive
    let learnedNames = [];
    let learnedKey = '';
    // Every name seen, learned or blocked. Only ever grows, so a name is sent for learning at most
    // once per page – no write/rescan feedback loop.
    const knownNames = new Set();
    let detector = FM.createDetector(settings, learnedNames);
    let css = FM.buildCss(settings);
    let staticList = FM.staticSelectorList(settings); // CSS-only masked elements, or null
    const personList = FM.personSelectorList();
    const workspaceList = FM.WORKSPACE_NAME_SELECTORS_LIST();
    const roots = new Set(); // Document and ShadowRoots we observe
    const styleEls = new Map(); // root -> <style>
    const svgEls = new Map(); // root -> hidden <svg> with the mosaic filter
    let pollTimer = null;
    let lastInputValues = new WeakMap(); // input -> last evaluated value
    let pageTitle = null;
    let lastSetTitle = null;
    let picker = null;
    let lastContextTarget = null; // element of the last (trusted) right-click, for the context menu
    const pendingNames = new Set();
    // New fake overlays whose positioning still has to be checked (batched: reading computed style
    // between DOM writes would force a style recalculation per element).
    const pendingPositions = new Set();
    let learnTimer = null;
    let curtainOn = false;
    let curtainHost = null;
    let badgeHost = null;
    let badgeText = null;

    const observer = new window.MutationObserver(onMutations);
    const OBSERVE_OPTIONS = { childList: true, subtree: true, characterData: true, attributes: true, attributeFilter: ['title'] };

    const isFake = () => settings.enabled && settings.mode === 'fake';
    const isLearning = () => settings.enabled && settings.categories.learnedNames;

    // ---------------------------------------------------------------- styles

    function ensureStyle(rootNode) {
      const parent = rootNode === document ? document.documentElement : rootNode;
      let el = styleEls.get(rootNode);
      if (!el) {
        el = document.createElement('style');
        el.setAttribute(STYLE_MARKER, '');
        el.textContent = css;
        styleEls.set(rootNode, el);
      }
      if (!el.isConnected && parent) parent.appendChild(el);
      // filter: url(#id) resolves within the element's own tree, so every styled root gets the filter.
      let svg = svgEls.get(rootNode);
      if (!svg) {
        svg = FM.renderPixelateSvg(document, FM.pixelSize(settings));
        svg.setAttribute(STYLE_MARKER, '');
        svgEls.set(rootNode, svg);
      }
      if (!svg.isConnected && parent) parent.appendChild(svg);
    }

    function applyCss() {
      css = FM.buildCss(settings);
      const size = FM.pixelSize(settings);
      for (const [rootNode, el] of styleEls) {
        if (el.textContent !== css) el.textContent = css;
        const svg = svgEls.get(rootNode);
        if (svg) FM.renderPixelateSvg(document, size, svg);
        ensureStyle(rootNode);
      }
    }

    // ------------------------------------------------------------- detection

    function isFormField(el) {
      return (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') && el.matches(INPUT_SELECTOR);
    }

    function isSensitive(el) {
      if (!detector.active) return false;
      let textNodes = 0;
      for (let n = el.firstChild; n; n = n.nextSibling) {
        if (n.nodeType !== 3) continue;
        textNodes++;
        if (detector.test(n.data)) return true;
      }
      // Adjacent text nodes (e.g. Angular interpolation "{{user}}@{{domain}}")
      if (textNodes > 1 && detector.test(ownText(el))) return true;
      if (isFormField(el) && detector.test(el.value)) return true;
      if (el.matches(CODE_LINE_SELECTOR) && detector.test(el.textContent)) return true;
      if (el.firstElementChild && hasOwnText(el) && hasOnlyInlineChildren(el)) {
        const text = el.textContent;
        if (text.length <= MAX_COMBINED_TEXT && detector.test(text)) return true;
      }
      return false;
    }

    function ownText(el) {
      let text = '';
      for (let n = el.firstChild; n; n = n.nextSibling) if (n.nodeType === 3) text += n.data;
      return text;
    }

    function hasOwnText(el) {
      for (let n = el.firstChild; n; n = n.nextSibling) {
        if (n.nodeType === 3 && n.data.trim()) return true;
      }
      return false;
    }

    function hasOnlyInlineChildren(el) {
      for (let c = el.firstElementChild; c; c = c.nextElementSibling) {
        if (!INLINE_TAGS.has(c.tagName) || c.firstElementChild) return false;
      }
      return true;
    }

    function safeMatches(el, selectorList) {
      try {
        return Boolean(selectorList) && el.matches(selectorList);
      } catch {
        return false;
      }
    }

    function evaluate(el) {
      if (!el || el.nodeType !== 1 || SKIP_TAGS.has(el.tagName)) return;
      if (el.hasAttribute(STYLE_MARKER)) return;
      const sensitive = settings.enabled && isSensitive(el);
      if (sensitive) {
        if (!el.hasAttribute(MASK_ATTR)) {
          el.setAttribute(MASK_ATTR, '');
          const rootNode = el.getRootNode();
          if (rootNode !== document && !styleEls.has(rootNode)) styleShadowRootIfNeeded(rootNode);
        }
      } else if (el.hasAttribute(MASK_ATTR)) {
        el.removeAttribute(MASK_ATTR);
      }

      const isPerson = (isLearning() || isFake()) && safeMatches(el, personList);
      if (isPerson && isLearning()) learnFrom(el);
      // Person fields only show a fake when the "signed-in user" category masks them at all.
      const personFake = isPerson && settings.categories.userProfile;
      updateFake(el, sensitive, personFake);
      if (el.hasAttribute('title') || el.hasAttribute(TITLE_ATTR)) processTitle(el);
    }

    function scan(node) {
      if (!node) return;
      if (node.nodeType === 3) {
        evaluate(node.parentElement);
        return;
      }
      if (node.nodeType === 1) {
        if (SKIP_TAGS.has(node.tagName) || node.hasAttribute(STYLE_MARKER)) return;
        evaluate(node);
        attachShadowOf(node);
      } else if (node.nodeType !== 9 && node.nodeType !== 11) {
        return;
      }
      const walker = document.createTreeWalker(node, 1 /* SHOW_ELEMENT */, {
        acceptNode: (el) => (SKIP_TAGS.has(el.tagName) || el.hasAttribute(STYLE_MARKER) ? 2 /* REJECT subtree */ : 1)
      });
      for (let el = walker.nextNode(); el; el = walker.nextNode()) {
        evaluate(el);
        attachShadowOf(el);
      }
    }

    function shadowRootOf(el) {
      if (el.shadowRoot) return el.shadowRoot;
      // Closed shadow roots are reachable for extensions via chrome.dom (custom elements only,
      // which are the only elements that can host one besides a few built-ins).
      if (el.localName.includes('-') && chrome && chrome.dom && chrome.dom.openOrClosedShadowRoot) {
        try {
          return chrome.dom.openOrClosedShadowRoot(el);
        } catch {
          return null;
        }
      }
      return null;
    }

    function attachShadowOf(el) {
      const sr = shadowRootOf(el);
      if (sr) attachRoot(sr);
    }

    // Shadow roots get the stylesheet + filter only once they contain something to mask. Fabric
    // has many small shadow roots (e.g. one per tooltip) that only hold a <slot>; giving each of
    // them a <style> and an <svg> made style recalculation needlessly expensive.
    function styleShadowRootIfNeeded(rootNode) {
      if (rootNode === document || styleEls.has(rootNode) || !roots.has(rootNode)) return;
      let needed = Boolean(rootNode.querySelector(`[${MASK_ATTR}]`));
      if (!needed && staticList) {
        try {
          needed = Boolean(rootNode.querySelector(staticList));
        } catch {
          needed = false;
        }
      }
      if (needed) ensureStyle(rootNode);
    }

    function attachRoot(rootNode) {
      if (roots.has(rootNode)) return;
      roots.add(rootNode);
      if (rootNode === document) ensureStyle(rootNode);
      observer.observe(rootNode, OBSERVE_OPTIONS);
      scan(rootNode);
      styleShadowRootIfNeeded(rootNode);
    }

    function rescanAll() {
      for (const rootNode of roots) scan(rootNode);
    }

    function touch(touched, el) {
      if (!el || el.nodeType !== 1) return;
      touched.add(el);
      touched.add(el.parentElement); // combined inline text may have changed
      const line = el.closest(CODE_LINE_SELECTOR);
      if (line) touched.add(line);
    }

    function onMutations(mutations) {
      const touched = new Set();
      let removedSomething = false;
      for (const m of mutations) {
        if (m.type === 'characterData') {
          touch(touched, m.target.parentElement);
        } else if (m.type === 'childList') {
          touch(touched, m.target);
          for (const added of m.addedNodes) {
            if (added.nodeType !== 1) continue;
            scan(added);
            const rootNode = added.getRootNode();
            if (rootNode !== document && !styleEls.has(rootNode)) styleShadowRootIfNeeded(rootNode);
          }
          if (m.removedNodes.length) removedSomething = true;
        } else if (m.type === 'attributes') {
          // Our own title writes come back here too; processTitle() recognizes and ignores them.
          if (m.target.nodeType === 1 && m.target.getAttribute(TITLE_SET_ATTR) !== m.target.getAttribute('title')) {
            processTitle(m.target);
          }
        }
      }
      for (const el of touched) evaluate(el);
      flushPositions();
      // Our elements may have been removed directly, or with their parent (re-rendered <html>,
      // document.open() in about:blank frames).
      if (removedSomething) {
        for (const [rootNode, el] of styleEls) {
          const svg = svgEls.get(rootNode);
          if (!el.isConnected || (svg && !svg.isConnected)) ensureStyle(rootNode);
        }
        if (curtainOn && curtainHost && !curtainHost.isConnected) document.documentElement.appendChild(curtainHost);
        if (badgeHost && settings.preview && !badgeHost.isConnected) document.documentElement.appendChild(badgeHost);
      }
      if (isTopFrame) updateTitle();
    }

    // ------------------------------------------------------------- fake data

    function maskText(text) {
      return isFake()
        ? detector.replace(text, (match, kind) => FM.fake.fakeFor(kind, match))
        : detector.redact(text);
    }

    /**
     * Fake version of `text`: detected values become fakes; the rest stays readable only for short
     * labels and code lines, otherwise it is scrambled too.
     */
    function fakeOf(text, keepRest) {
      const fakes = [];
      const marked = detector.replace(text, (match, kind) => {
        fakes.push(FM.fake.fakeFor(kind, match));
        return `\uE000${fakes.length - 1}\uE000`;
      });
      const rest = marked.replace(/\uE000\d+\uE000/g, '').replace(/[^\p{L}\p{N}]/gu, '');
      const parts = marked.split(/(\uE000\d+\uE000)/);
      const scrambleRest = !keepRest && rest.length > MAX_CLEAR_LABEL;
      return parts
        .map((part) => {
          const m = /^\uE000(\d+)\uE000$/.exec(part);
          if (m) return fakes[Number(m[1])];
          return scrambleRest ? FM.fake.scramble(part) : part;
        })
        .join('');
    }

    function containsOtherMasked(el) {
      if (!staticList) return false;
      try {
        return Boolean(el.querySelector(staticList)) || Boolean(el.querySelector(personList));
      } catch {
        return false;
      }
    }

    function fakeTextFor(el, sensitive, isPerson) {
      if (isFormField(el)) return null; // inputs cannot show ::after – mosaic
      const raw = el.textContent;
      if (!raw || !raw.trim() || raw.length > MAX_FAKE_TEXT) return null;
      const text = raw.trim();
      if (isPerson) return FM.fake.fakeNameList(text);
      const isStatic = staticList && safeMatches(el, staticList);
      // Nested fields masked by selectors would otherwise end up in clear text in our overlay.
      if (!isStatic && containsOtherMasked(el)) return null;
      if (sensitive) return fakeOf(text, el.matches(CODE_LINE_SELECTOR));
      if (isStatic) {
        if (el.querySelector('img, svg, canvas')) return null; // avatars & logos: mosaic
        if (safeMatches(el, workspaceList)) return FM.fake.fakeWorkspace(text);
        const replaced = fakeOf(text, false);
        return replaced !== text ? replaced : FM.fake.scramble(text);
      }
      return null;
    }

    function updateFake(el, sensitive, isPerson) {
      let fake = isFake() && (sensitive || isPerson || (staticList && safeMatches(el, staticList)))
        ? fakeTextFor(el, sensitive, isPerson)
        : null;
      // A "fake" identical to the original would reveal it: mosaic instead.
      if (fake !== null && fake.trim() === el.textContent.trim()) fake = null;
      if (fake) {
        if (!el.hasAttribute(FAKE_ATTR)) pendingPositions.add(el);
        if (el.getAttribute(FAKE_ATTR) !== fake) el.setAttribute(FAKE_ATTR, fake);
      } else if (el.hasAttribute(FAKE_ATTR)) {
        el.removeAttribute(FAKE_ATTR);
        el.removeAttribute(FAKE_POS_ATTR);
        pendingPositions.delete(el);
      }
    }

    /** The overlay needs a positioned anchor; add one only where the page has none. */
    function flushPositions() {
      if (!pendingPositions.size) return;
      const elements = [...pendingPositions];
      pendingPositions.clear();
      // All reads first (one style recalculation), then all writes.
      const statics = elements.filter((el) => {
        if (!el.isConnected) return false;
        const position = window.getComputedStyle(el).position;
        return !position || position === 'static';
      });
      for (const el of statics) el.setAttribute(FAKE_POS_ATTR, '');
    }

    // -------------------------------------------------------------- tooltips

    function insideMasked(el) {
      if (el.closest(`[${MASK_ATTR}]`)) return true;
      if (!staticList) return false;
      try {
        return Boolean(el.closest(staticList));
      } catch {
        return false;
      }
    }

    /** Masks the native tooltip (title attribute) of masked elements and of sensitive titles. */
    function processTitle(el) {
      const stored = el.getAttribute(TITLE_ATTR);
      const current = el.getAttribute('title');
      const ours = el.getAttribute(TITLE_SET_ATTR);
      if (current === null) {
        // The page removed the tooltip: forget it, do not resurrect it.
        if (stored !== null) el.removeAttribute(TITLE_ATTR);
        if (ours !== null) el.removeAttribute(TITLE_SET_ATTR);
        return;
      }
      // A title different from what we set came from the page and is the new original.
      const original = current !== ours ? current : stored;
      const mask = settings.enabled && settings.stripTooltips && original &&
        (detector.test(original) || insideMasked(el));
      if (mask) {
        let masked = maskText(original);
        if (masked === original) masked = isFake() ? FM.fake.scramble(original) : MASKED_TITLE;
        if (masked === original) masked = MASKED_TITLE;
        if (stored !== original) el.setAttribute(TITLE_ATTR, original);
        if (current !== masked) {
          el.setAttribute(TITLE_SET_ATTR, masked);
          el.setAttribute('title', masked);
        }
      } else if (stored !== null) {
        el.removeAttribute(TITLE_ATTR);
        el.removeAttribute(TITLE_SET_ATTR);
        if (current === ours) el.setAttribute('title', stored);
      }
    }

    // --------------------------------------------------------- learned names

    function learnFrom(el) {
      for (const name of FM.extractNames(el.textContent)) {
        if (!knownNames.has(name.toLowerCase())) pendingNames.add(name);
      }
      if (pendingNames.size && !learnTimer) learnTimer = window.setTimeout(flushLearned, LEARN_FLUSH_MS);
    }

    function flushLearned() {
      learnTimer = null;
      const names = [...pendingNames];
      pendingNames.clear();
      for (const n of names) knownNames.add(n.toLowerCase());
      if (!names.length) return;
      // The service worker merges names from all frames and tabs in one place.
      try {
        chrome.runtime.sendMessage({ type: MSG.LEARN_NAMES, names }).catch(() => {});
      } catch {
        // extension context invalidated
      }
    }

    function applyLearnedNames(list) {
      const next = FM.normalizeLearned(list);
      for (const n of next) knownNames.add(n.toLowerCase());
      const key = next.map((n) => n.toLowerCase()).sort().join('\n');
      if (key === learnedKey) return; // unchanged: no rebuild, no rescan
      learnedKey = key;
      learnedNames = next;
      refresh();
    }

    function applyBlockedNames(list) {
      for (const n of list || []) if (typeof n === 'string') knownNames.add(n.toLowerCase());
    }

    // ---------------------------------------------------------------- inputs

    function poll() {
      if (startedWithRuntime && !(chrome.runtime && chrome.runtime.id)) {
        stop(); // orphaned after an extension update; the new copy takes over
        return;
      }
      if (document.visibilityState === 'hidden') return; // background tab
      for (const rootNode of roots) {
        if (rootNode.host && !rootNode.host.isConnected) {
          // Detached shadow host: stop tracking (it is re-attached by scan() if it comes back).
          roots.delete(rootNode);
          styleEls.delete(rootNode);
          svgEls.delete(rootNode);
          continue;
        }
        if (!rootNode.querySelectorAll || !detector.active) continue;
        for (const el of rootNode.querySelectorAll(INPUT_SELECTOR)) {
          // Frameworks set .value without events; only re-test values that changed.
          if (lastInputValues.get(el) === el.value) continue;
          lastInputValues.set(el, el.value);
          evaluate(el);
        }
      }
      if (isTopFrame && settings.preview) updateBadge();
    }

    function onContextMenu(event) {
      if (!event.isTrusted) return;
      const path = typeof event.composedPath === 'function' ? event.composedPath() : [];
      const el = path.find((n) => n && n.nodeType === 1) || event.target;
      lastContextTarget = el && el.nodeType === 1 ? el : null;
    }

    /** Context menu "always hide this element": same selector logic as the element picker. */
    async function hideContextElement() {
      const el = lastContextTarget;
      if (!el || !el.isConnected) return null;
      const selector = FM.generateSelector(el);
      await FM.addCustomSelector(selector);
      return selector;
    }

    function onInputEvent(event) {
      const path = typeof event.composedPath === 'function' ? event.composedPath() : [];
      evaluate(path[0] || event.target);
    }

    function updatePolling() {
      const shouldPoll = settings.enabled && (detector.active || settings.preview);
      if (shouldPoll && !pollTimer) pollTimer = window.setInterval(poll, POLL_MS);
      if (!shouldPoll && pollTimer) {
        window.clearInterval(pollTimer);
        pollTimer = null;
      }
    }

    // ----------------------------------------------------------------- title

    function updateTitle() {
      const current = document.title;
      if (current !== lastSetTitle) pageTitle = current; // the page changed its title
      if (pageTitle === null) return;
      const desired = settings.enabled && settings.maskTitle ? maskText(pageTitle) : pageTitle;
      if (desired !== current) {
        lastSetTitle = desired;
        document.title = desired;
      } else {
        lastSetTitle = current;
      }
    }

    // ------------------------------------------------------ curtain & badge

    /** A host element with a closed shadow root, ignored by scan(). */
    function createOverlayHost(tag, cssText) {
      const host = document.createElement(tag);
      host.setAttribute(STYLE_MARKER, '');
      const shadow = host.attachShadow({ mode: 'closed' });
      const style = document.createElement('style');
      style.textContent = cssText;
      shadow.appendChild(style);
      return { host, shadow };
    }

    function setCurtain(on) {
      curtainOn = Boolean(on);
      if (!isTopFrame) return;
      if (curtainOn) {
        if (!curtainHost) {
          const { host, shadow } = createOverlayHost('fab-mask-curtain',
            ':host{all:initial!important;position:fixed!important;inset:0!important;z-index:2147483647!important;' +
            'display:flex!important;align-items:center!important;justify-content:center!important;background:#f3f2f1!important;' +
            'font:15px/1.5 "Segoe UI",system-ui,sans-serif!important;color:#424242!important;}' +
            '@media (prefers-color-scheme:dark){:host{background:#1f1f1f!important;color:#d6d6d6!important;}}' +
            '.box{text-align:center;max-width:420px;padding:24px;}' +
            '.title{font-size:20px;font-weight:600;margin-bottom:6px;}.hint{opacity:.75;}');
          const box = document.createElement('div');
          box.className = 'box';
          const title = document.createElement('div');
          title.className = 'title';
          title.textContent = t('curtainTitle');
          const hint = document.createElement('div');
          hint.className = 'hint';
          hint.textContent = t('curtainHint');
          box.append(title, hint);
          shadow.appendChild(box);
          curtainHost = host;
        }
        if (!curtainHost.isConnected) document.documentElement.appendChild(curtainHost);
      } else if (curtainHost) {
        curtainHost.remove();
      }
    }

    function updateBadge() {
      if (!isTopFrame) return;
      if (!settings.enabled || !settings.preview) {
        if (badgeHost) badgeHost.remove();
        return;
      }
      if (!badgeHost) {
        const { host, shadow } = createOverlayHost('fab-mask-badge',
          `:host{all:initial!important;position:fixed!important;right:16px!important;bottom:16px!important;` +
          `z-index:2147483646!important;pointer-events:none!important;}` +
          `.b{font:600 12px/1.4 "Segoe UI",system-ui,sans-serif;color:#fff;background:${FM.PREVIEW_COLOR};` +
          'padding:6px 10px;border-radius:6px;box-shadow:0 2px 8px rgba(0,0,0,.25);}');
        badgeText = document.createElement('div');
        badgeText.className = 'b';
        shadow.appendChild(badgeText);
        badgeHost = host;
      }
      let count = document.querySelectorAll(`[${MASK_ATTR}]`).length;
      if (staticList) {
        try {
          count += document.querySelectorAll(staticList).length;
        } catch {
          // ignore invalid custom selector
        }
      }
      badgeText.textContent = t('previewBadge', [String(count)]);
      if (!badgeHost.isConnected) document.documentElement.appendChild(badgeHost);
    }

    // -------------------------------------------------------------- settings

    function refresh() {
      detector = FM.createDetector(settings, learnedNames);
      staticList = FM.staticSelectorList(settings);
      lastInputValues = new WeakMap();
      applyCss();
      rescanAll();
      flushPositions();
      for (const rootNode of roots) styleShadowRootIfNeeded(rootNode);
      updatePolling();
      if (isTopFrame) {
        updateTitle();
        updateBadge();
      }
    }

    function applySettings(raw) {
      settings = FM.normalizeSettings(raw);
      refresh();
    }

    function onStorageChanged(changes, areaName) {
      const next = FM.settingsFromChange(changes, areaName);
      if (next) applySettings(next);
      const names = FM.valueFromChange(changes, areaName, FM.LEARNED_KEY, FM.normalizeLearned);
      if (names) applyLearnedNames(names);
      const blocked = FM.valueFromChange(changes, areaName, FM.BLOCKED_KEY, (v) => (Array.isArray(v) ? v : []));
      if (blocked) applyBlockedNames(blocked);
      const salt = FM.valueFromChange(changes, areaName, FM.SALT_KEY, (v) => (typeof v === 'string' ? v : ''));
      if (salt !== undefined) {
        FM.fake.setSalt(salt);
        refresh();
      }
      const curtain = FM.valueFromChange(changes, areaName, FM.CURTAIN_KEY, (v) => v === true);
      if (curtain !== undefined) setCurtain(curtain);
    }

    // ---------------------------------------------------------------- picker

    function getPicker() {
      if (!picker) {
        picker = FM.createPicker({
          attr: FM.PICKER_ATTR,
          onPick: async (selector) => {
            let saved = true;
            try {
              await FM.updateSettings((s) => {
                if (!s.customSelectors.includes(selector)) s.customSelectors.push(selector);
                return s;
              });
            } catch {
              saved = false;
            }
            notifyPickerDone(saved ? selector : null);
          },
          onCancel: () => notifyPickerDone(null)
        });
      }
      return picker;
    }

    function notifyPickerDone(selector) {
      try {
        chrome.runtime.sendMessage({ type: MSG.PICKER_DONE, selector }).catch(() => {});
      } catch {
        // extension context invalidated (extension reloaded) – nothing to notify
      }
    }

    function onMessage(message, _sender, sendResponse) {
      if (!message || typeof message.type !== 'string') return undefined;
      switch (message.type) {
        case MSG.PING:
          if (isTopFrame) sendResponse({ ok: true, enabled: settings.enabled });
          return undefined;
        case MSG.START_PICKER:
          getPicker().start();
          return undefined;
        case MSG.STOP_PICKER:
          if (picker) picker.stop();
          return undefined;
        case MSG.HIDE_CONTEXT_ELEMENT:
          hideContextElement().then((selector) => sendResponse({ ok: Boolean(selector), selector }), () => sendResponse({ ok: false }));
          return true; // async response
        default:
          return undefined;
      }
    }

    // ----------------------------------------------------------------- start

    async function loadStored() {
      const [stored, names, blocked, curtain, salt] = await Promise.all([
        FM.loadSettings(), FM.loadLearnedNames(), FM.loadBlockedNames(), FM.getCurtain(), FM.loadFakeSalt()
      ]);
      setCurtain(curtain);
      FM.fake.setSalt(salt);
      settings = FM.normalizeSettings(stored);
      applyBlockedNames(blocked);
      learnedKey = null; // force one refresh with the loaded settings
      applyLearnedNames(names);
    }

    function start() {
      attachRoot(document);
      flushPositions();
      document.addEventListener('input', onInputEvent, true);
      document.addEventListener('change', onInputEvent, true);
      document.addEventListener('contextmenu', onContextMenu, true);
      updatePolling();
      if (isTopFrame) updateTitle();
      if (chrome && chrome.storage) {
        chrome.storage.onChanged.addListener(onStorageChanged);
        loadStored().catch(() => applySettings(null));
      }
      if (chrome && chrome.runtime && chrome.runtime.onMessage) {
        chrome.runtime.onMessage.addListener(onMessage);
      }
    }

    function stop() {
      observer.disconnect();
      document.removeEventListener('input', onInputEvent, true);
      document.removeEventListener('change', onInputEvent, true);
      document.removeEventListener('contextmenu', onContextMenu, true);
      if (pollTimer) window.clearInterval(pollTimer);
      pollTimer = null;
      if (learnTimer) window.clearTimeout(learnTimer);
      learnTimer = null;
      if (picker) picker.stop();
      try {
        if (chrome && chrome.storage) chrome.storage.onChanged.removeListener(onStorageChanged);
        if (chrome && chrome.runtime && chrome.runtime.onMessage) chrome.runtime.onMessage.removeListener(onMessage);
      } catch {
        // extension context already invalidated
      }
    }

    return {
      start,
      stop,
      applySettings,
      applyLearnedNames,
      setCurtain,
      flushLearned,
      hideContextElement,
      pollInputs: poll,
      getSettings: () => settings
    };
  }

  const api = { createMasker };
  root.FabricMask = Object.assign(root.FabricMask || {}, api);
  if (typeof module !== 'undefined' && module.exports) module.exports = api;

  // Auto-start inside the extension (guards against double injection).
  const chromeApi = root.chrome;
  if (chromeApi && chromeApi.runtime && chromeApi.runtime.id && root.document && !root.__fabricMaskStarted) {
    root.__fabricMaskStarted = true;
    createMasker({ window: root, chrome: chromeApi, FabricMask: root.FabricMask }).start();
  }
})(typeof globalThis !== 'undefined' ? globalThis : this);
